name: 'Staging: Build and Deploy'

on:
  push:
    branches:
      - 'feature/**'
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.5.0

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Configuration
      run: |
        cd ./infrastructure/terraform
        echo "terraform {
          backend \"azurerm\" {
            storage_account_name = \"terraformstatekalvinsub\"
            container_name       = \"staging\"
            key                  = \"portfolio/webapp.tfstate\"
            access_key           = \"${{ secrets.TERRAFORM_STATE_ACCESS_KEY }}\"
          }
        }" > backend.tf

    - name: Terraform Init
      run: |
        cd ./infrastructure/terraform
        terraform init

    - name: Terraform Validate
      run: |
        cd ./infrastructure/terraform
        terraform validate

    - name: Terraform Apply
      run: |
        cd ./infrastructure/terraform
        terraform apply -auto-approve -var-file=staging.tfvars
    
    - name: Read Terraform Outputs
      id: read-outputs
      run: |
        OUTPUTS=$(terraform output -json)
        echo "terraform-outputs=$OUTPUTS" >> $GITHUB_OUTPUT

    - name: Write Terraform Outputs
      run: |
        echo "${{ steps.read-outputs.outputs.terraform-outputs }}"

  build_and_deploy:
    needs: [terraform]
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          
      - name: NPM install
        run: |
          cd app
          npm ci

      - name: Run lint
        run: 
          cd app
          npm run lint --if-present

      - name: Run build
        run:
          cd app
          npm run build --if-present
        
      - name: Run unit tests
        run:
          cd app
          npm run test:unit

      - name: Upload content
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            cd app
            az storage blob upload-batch --account-name ${{ steps.read-outputs.outputs.terraform-outputs.storage_account_name.value }} --destination <container-name> --source dist --pattern "*.*"